# proxypool remote server url. Blank for http://127.0.0.1:8080
server_url:
  - http://192.168.2.1/clash/proxies
  - http://192.168.2.1/clash/proxies


# For your local server
request: http   # http / https
domain:         # default: 127.0.0.1
port:           # default: 80

cron_interval: 15 # default: 15  minutes
show_remote_speed: true # default false

speedtest:      # default false
connection:     # default 5
timout:         # default 10
